### PR TITLE
Sort script output by file size

### PR DESCRIPTION
**Pull request by LefterisJP**
Hey and thanks for the script. Came across it while looking at the archlinux pacman wiki.

To quickly see which of the listed files would need my attention for cleanup, I made a small modification to also add file size and sort by it. 

If you find it useful you can merge it.

### CODE REVIEW

**Comment by graysky2** [comment]
I'd like to roll this into a getopt call but am getting stuck on how to make the different filtered options on the `comm` output into a variable.  Any thought?

See: https://github.com/graysky2/lostfiles/commit/666aea79dc80a39cb0c981cb2a38d6fe7ab8d296

**Comment by graysky2** [comment]
OK, please try 10134ca526df5aa3b9b2330d55e257d029af9b98

**Comment by LefterisJP** [comment]
hello, yeah that works fine

**Comment by graysky2** [comment]
:+1:

**Pull request closed without merging**
